FROM node:12.15.0-alpine
WORKDIR /usr/src/app

COPY package.json yarn.lock /usr/src/app/
RUN yarn

COPY . /usr/src/app
RUN apk add --no-cache curl \
  && curl -sf https://gobinaries.com/tj/node-prune | sh \
  && which node-prune \
  && node-prune

CMD ["node", "index.js"]
